#version 430

layout (binding = 0, rgba32f) uniform image2D paint;

uniform ivec2 offset;
uniform ivec2 position;
uniform float radius;
uniform vec3 color;

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main(){
    ivec2 curPos = ivec2(gl_GlobalInvocationID.xy) + offset;
    if (length(curPos - position) <= radius){
        vec3 src = imageLoad(paint, curPos).xyz;
        imageStore(paint, curPos, vec4(clamp(src * color, 0.0, 1.0), 1.0));
    }
}
