/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103095-g2323d3a923-20210729"
#endif /* AVUTIL_FFVERSION_H */
