#version 430

layout (binding = 0, rgba32f) uniform image2D paint;

layout (binding = 1) uniform Brush {
    ivec2 offset;
    ivec2 position;
    float radius;
    vec3 color;
};

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main(){
    ivec2 curPos = ivec2(gl_GlobalInvocationID.xy) + offset;
    if (length(curPos - position) <= radius){
        imageStore(paint, ivec2(curPos), vec4(color, 1.0));
    }
}